# Generated by Django 4.1.3 on 2023-01-08 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_shop_app', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='name',
            new_name='type_name',
        ),
    ]
