# Generated by Django 4.1.3 on 2023-01-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
