# Generated by Django 4.1.3 on 2022-11-12 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_shop_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='pastry_shop_api.customer'),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='special_request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customproduct',
            name='topper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_products', to='pastry_shop_api.producttopper'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='custom_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='pastry_shop_api.customproduct'),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='pastry_shop_api.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='topper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pastry_shop_api.producttopper'),
        ),
    ]
