# Generated by Django 4.1.3 on 2022-11-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_shop_app', '0002_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=45),
        ),
    ]
