# Generated by Django 4.1.3 on 2022-11-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_shop_api', '0002_alter_account_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='producttopper',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='price',
            field=models.FloatField(),
        ),
    ]
