# Generated by Django 4.1.3 on 2023-01-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_shop_app', '0003_rename_name_producttype_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='type_name',
            new_name='name',
        ),
    ]
