# Generated by Django 4.1.3 on 2022-11-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_shop_app', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
