# Generated by Django 4.1.3 on 2022-11-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastry_shop_app', '0005_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
