# Generated by Django 4.1.3 on 2023-01-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_basket_commodity_pay_remove_order_book_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay',
            options={'ordering': ('order',)},
        ),
    ]
